config/routes.rb
Rails.application.routes.draw do
  root to: 'ads#index'
  get 'users/login', to: 'login#new'
  post 'users/login', to: 'login#create'
  resources :users, only:  [:new, :create]
  get 'ads/machine', as: 'machine_ads', to:'ads#machine'
  get 'ads/truck', as: 'truck_ads', to:'ads#truck'
  get 'ads/update_models', as: 'update_models'
  get 'ads/:id/update_models', to:'ads#update_models'
  resources :ads
  resources :models
  resources :automakers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :type
  belongs_to :automaker
  belongs_to :model
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_presence_of :type, :automaker, :model
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :user_logged , only: [:new, :edit, :create, :destroy, :update]
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
    @models = []
  end

  # GET /ads/1/edit
  def edit
    @models = []
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html {redirect_to @ad, notice: 'Ad was successfully created.'}
        format.json {render :show, status: :created, location: @ad}
      else
        format.html {render :new}
        format.json {render json: @ad.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html {redirect_to @ad, notice: 'Ad was successfully updated.'}
        format.json {render :show, status: :ok, location: @ad}
      else
        format.html {render :edit}
        format.json {render json: @ad.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html {redirect_to ads_url, notice: 'Ad was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def update_models
    @models = Model.where("automaker_id = ?", params[:automaker_id])
    respond_to do |format|
      format.js
    end
  end

  def edit_update_models
    @models = Model.where("automaker_id = ?", params[:automaker_id])
    respond_to do |format|
      format.js
    end
  end

  def machine
    @ads = Ad.where :type_id => 2
  end

  def truck
    @ads = Ad.where :type_id => 1
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ad
    @ad = Ad.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ad_params
    params.require(:ad).permit(:type_id, :automaker_id, :model_id, :price, :avatar)
  end

  def user_logged
    unless current_user
      redirect_to root_path, alert: 'Você precisa estar logado para executar esta ação!'
    end
  end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_exhibition.html.erb
<p id="notice"><%= notice %></p>

<h1>TRUCADINHO</h1>
<% @ads.each do |ad| %>
    <div class="col-md-4 col-sm-4 mb">
      <div class="white-panel gn">
        <a href="<%= ad_path(ad) %>">
          <div class="white-header">
            <h5><%= ad.model.name %></h5>
          </div>
          <div class="centered">
            <% if ad.avatar.url %>
                <%= image_tag ad.avatar.url(:thumb) %>
            <% end %>
          </div>
          <div class="row">
            <p><strong>Fábricante: <%= ad.automaker.name %></strong></p>
            <p><strong>Ano: <%= ad.year %></strong></p>
            <% if ad.price.present? %>
                <p><strong>Preço: <%= ad.price %></strong></p>
            <% else %>
                <p><strong>Preço: A negociar!</strong></p>
            <% end %>
            <div class="clearfix"></div>
          </div>
          <div class="clearfix"></div>
        </a>
        <% if current_user %>
            <div class="row">
              <%= link_to 'Editar', edit_ad_path(ad), class: 'btn btn-primary btn-xs' %>
              <%= link_to 'Excluir', ad, method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: 'Are you sure?'} %>
            </div>
        <% end %>
      </div>
      <div class="clearfix"></div>
    </div>
<% end %>

app/views/ads/_form.html.erb
<div class="form-panel">
  <%= form_with(model: ad, local: true, html: {class: 'form-horizontal style-form', multipart: true}) do |form| %>
      <% if ad.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

            <ul>
              <% ad.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label">Foto:</label>
        <div class="col-sm-10">
          <%= form.file_field :avatar, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label 'Tipo', class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= collection_select(:ad, :type_id, Type.all, :id, :name, {prompt: true}, class: 'form-control') %>
        </div>
      </div>

      <div class="form-group">

        <%= form.label 'Fabricante', class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= collection_select(:ad, :automaker_id, Automaker.all, :id, :name, {prompt: true}, class: 'form-control', id: 'automakers') %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label 'Modelo', class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= form.select :model_id, options_for_select([['Please Select', nil], @models.collect {|model|
            [model.name.titleize, model.id]}], 0), {}, {id: 'models', class: 'form-control'} %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label 'Ano', class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= form.text_field :price, id: :ad_price, class: 'form-control' %>
        </div>
      </div>


      <div class="form-group">
        <%= form.label 'Preço', class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= form.text_field :price, id: :ad_price, class: 'form-control' %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit 'savar', class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<%= render 'exhibition'%>

app/views/ads/machine.html.erb
<%= render 'exhibition'%>

app/views/ads/new.html.erb
<h1 class="centered">Novo Anúncio</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<div class="container">
  <div class="container-fluid white-panel">
    <p id="notice"><%= notice %></p>
    <div class="centered">
      <% if @ad.present? %>
          <%= image_tag @ad.avatar.url(:medium) %>
      <% end %>
    </div>
    <h3 class="centered">
      <strong>Tipo:</strong>
      <%= @ad.type.name %>
    </h3>

    <h3 class="centered">
      <strong>Fabricante:</strong>
      <%= @ad.automaker.name %>
    </h3>

    <h3 class="centered">
      <strong>Modelo:</strong>
      <%= @ad.model.name %>
    </h3>
    <h3 class="centered">
      <strong>Ano:</strong>
      <%= @ad.year %>
    </h3>

    <h3 class="centered">
      <strong>Preço:</strong>
      <% if @ad.price.present? %>
          <%= @ad.price %>
      <% else %>
          A negociar
      <% end %>
    </h3>
    <% if current_user %>
        <%= link_to 'Editar', edit_ad_path(@ad) %> |
    <% end %>
    <%= link_to 'Votlar', ads_path %>
  </div>
</div>

app/views/ads/truck.html.erb
<%= render 'exhibition'%>