config/routes.rb
Rails.application.routes.draw do
  root to: 'ads#index'
  get 'users/login', to: 'login#new'
  post 'users/login', to: 'login#create'
  resources :users, only:  [:new, :create]
  get 'ads/machine', as: 'machine_ads', to:'ads#machine'
  get 'ads/truck', as: 'truck_ads', to:'ads#truck'
  get 'ads/update_models', as: 'update_models'
  get 'ads/:id/update_models', to:'ads#update_models'
  resources :ads
  resources :models
  resources :automakers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :type
  belongs_to :automaker
  belongs_to :model
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_presence_of :type, :automaker, :model
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automaker.rb
class Automaker < ApplicationRecord
  has_many :ads
  has_many :models
  validates_presence_of :name

end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :automaker
  validates_presence_of :automaker
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :ads
  validates_presence_of :name
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord

  validates_presence_of :email, :password
  validates_uniqueness_of :email
  validates_confirmation_of :password

  def password=(new_password)
    @password = new_password
    self.encrypted_password = BCrypt::Password.create(@password)
  end

  def password
    @password
  end

  def valid_password?(password_to_validate)
    BCrypt::Password.new(encrypted_password) == password_to_validate
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :automaker_id)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<div class="form-panel">
  <%= form_with(model: model, local: true) do |form| %>
      <% if model.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

            <ul>
              <% model.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= form.text_field :name, id: :model_name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :automaker,class:'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= collection_select(:model, :automaker_id, Automaker.all, :id, :name, {prompt: true}, class: 'form-control') %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
  <% end %>
</div>

app/views/models/_model.html.erb
<option value="<%= model.id %>"><%= model.name.titleize %></option>

app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form', model: @model %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<div class="content-panel">
  <p id="notice"><%= notice %></p>

  <h1 class="centered">Modelos</h1>
  <%= link_to 'Novo Modelo', new_model_path, class: 'btn btn-primary' %>
  <table class="table table-striped table-advance table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Automaker</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @models.each do |model| %>
        <tr>
          <td><%= model.name %></td>
          <td><%= model.automaker.name %></td>
          <td><%= link_to 'Show', model, class: 'btn btn-success btn-xs' %>
            <%= link_to 'Edit', edit_model_path(model), class: 'btn btn-primary btn-xs' %>
            <%= link_to 'Destroy', model, method: :delete, data: {confirm: 'Você tem certeza?'}, class: 'btn btn-danger btn-xs' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/models/new.html.erb
<h1 class="centered">Novo Modelo</h1>

<%= render 'form', model: @model %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @model.name %>
</p>

<p>
  <strong>Automaker:</strong>
  <%= @model.automaker.name %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>