config/routes.rb
Rails.application.routes.draw do
  root to: 'ads#index'
  get 'users/login', to: 'login#new'
  post 'users/login', to: 'login#create'
  resources :users, only:  [:new, :create]
  get 'ads/machine', as: 'machine_ads', to:'ads#machine'
  get 'ads/truck', as: 'truck_ads', to:'ads#truck'
  get 'ads/update_models', as: 'update_models'
  get 'ads/:id/update_models', to:'ads#update_models'
  resources :ads
  resources :models
  resources :automakers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/automaker.rb
class Automaker < ApplicationRecord
  has_many :ads
  has_many :models
  validates_presence_of :name

end

app/controllers/automakers_controller.rb
class AutomakersController < ApplicationController
  before_action :set_automaker, only: [:show, :edit, :update, :destroy]

  # GET /automakers
  # GET /automakers.json
  def index
    @automakers = Automaker.all
  end

  # GET /automakers/1
  # GET /automakers/1.json
  def show
  end

  # GET /automakers/new
  def new
    @automaker = Automaker.new
  end

  # GET /automakers/1/edit
  def edit
  end

  # POST /automakers
  # POST /automakers.json
  def create
    @automaker = Automaker.new(automaker_params)

    respond_to do |format|
      if @automaker.save
        format.html { redirect_to @automaker, notice: 'Automaker was successfully created.' }
        format.json { render :show, status: :created, location: @automaker }
      else
        format.html { render :new }
        format.json { render json: @automaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automakers/1
  # PATCH/PUT /automakers/1.json
  def update
    respond_to do |format|
      if @automaker.update(automaker_params)
        format.html { redirect_to @automaker, notice: 'Automaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @automaker }
      else
        format.html { render :edit }
        format.json { render json: @automaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automakers/1
  # DELETE /automakers/1.json
  def destroy
    @automaker.destroy
    respond_to do |format|
      format.html { redirect_to automakers_url, notice: 'Automaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automaker
      @automaker = Automaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def automaker_params
      params.require(:automaker).permit(:name)
    end
end

app/helpers/automakers_helper.rb
module AutomakersHelper
end

app/views/automakers/_form.html.erb
<div class="form-panel">
  <%= form_with(model: automaker, local: true) do |form| %>
      <% if automaker.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(automaker.errors.count, "error") %> prohibited this automaker from being saved:</h2>

            <ul>
              <% automaker.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, class: 'col-sm-2 col-sm-2 control-label' %>
        <div class="col-md-10">
          <%= form.text_field :name, id: :automaker_name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit 'savar', class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/automakers/edit.html.erb
<h1>Edição de Fabricante</h1>

<%= render 'form', automaker: @automaker %>

<%= link_to 'Show', @automaker %> |
<%= link_to 'Back', automakers_path %>

app/views/automakers/index.html.erb
<div class="content-panel">
  <p id="notice"><%= notice %></p>
  <h1 class="centered">Fabricantes</h1>
    <%= link_to 'Novo Fabricante', new_automaker_path, class: 'btn btn-primary' %>
    <table class="table table-striped table-advance table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @automakers.each do |automaker| %>
          <tr>
            <td><%= automaker.name %></td>
            <td><%= link_to 'Show', automaker %></td>
            <td><%= link_to 'Edit', edit_automaker_path(automaker) %></td>
            <td><%= link_to 'Destroy', automaker, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>


</div>

app/views/automakers/new.html.erb
<h1 class="centered">Novo Fabricante</h1>

<%= render 'form', automaker: @automaker %>

<%= link_to 'Back', automakers_path %>

app/views/automakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @automaker.name %>
</p>

<%= link_to 'Edit', edit_automaker_path(@automaker) %> |
<%= link_to 'Back', automakers_path %>