config/routes.rb
Rails.application.routes.draw do
  root to: 'ads#index'
  get 'users/login', to: 'login#new'
  post 'users/login', to: 'login#create'
  resources :users, only:  [:new, :create]
  get 'ads/machine', as: 'machine_ads', to:'ads#machine'
  get 'ads/truck', as: 'truck_ads', to:'ads#truck'
  get 'ads/update_models', as: 'update_models'
  get 'ads/:id/update_models', to:'ads#update_models'
  resources :ads
  resources :models
  resources :automakers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trucadinho</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'css/bootstrap', 'font-awesome/css/font-awesome', 'lineicons/style', 'css/style', 'css/style-responsive' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'bootstrap.min', 'jquery.scrollTo.min', 'jquery.nicescroll', 'jquery.sparkline', 'common-scripts' %>
</head>

<body>
<section id="container" class="sidebar-closed">
  <header class="header black-bg">
    <a href="<%= ads_path%>" class="logo"><b>Trucadinho</b></a>
    <div class="nav notify-row">
      <ul class="nav top-menu">
        <li><%= link_to 'Todos', ads_path %></li>
        <li><%= link_to 'Caminhões', truck_ads_url %></li>
        <li><%= link_to 'Máquinas', machine_ads_url %></li>
        <% if current_user %>
            <li><%= link_to 'Novo Anúncio', new_ad_path %></li>
            <li><%= link_to 'Fabricantes', automakers_path %></li>
            <li><%= link_to 'Modelos', models_path %></li>
      <% end %>
      </ul>
    </div>
    <div class="top-menu">
      <ul class="nav pull-right top-menu">
        <% if current_user %>
            <li><%= current_user.email %></li>
        <% else %>
            <li><%= link_to 'Login', users_login_path, class: 'logout' %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <asside>
  </asside>
  <section id="main-content">
    <section class="wrapper">
      <div class="row">
        <div class="col-lg-2 col-md-2">
          <div class="clearfix"></div>
        </div>
        <div class="col-lg-8 main-chart">
          <% if alert %>
              <div class="alert alert-danger">
                <%= alert %>
              </div>
          <% end %>

          <%= yield %>
        </div>
        <div class="col-lg-2 col-md-2">
          <div class="clearfix"></div>
        </div>
      </div>
    </section>
  </section>
</section>
</body>
</html>